In [1]:
8+8

16

In [2]:
import pandas as pd 
import tensorflow as tf
import keras_tuner as kt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

In [3]:
data=pd.read_csv('huge_1M_titanic.csv')

In [4]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [5]:
data=data.drop(columns=['PassengerId','Name','Age','Ticket','Cabin'])

In [6]:
data

        Survived  Pclass     Sex  SibSp  Parch        Fare Embarked
0              1       1  female      0      0   76.760165        C
1              0       3    male      0      0   10.193097        S
2              0       3    male      0      0   12.029416        C
3              0       3    male      0      0   13.429448        S
4              0       3    male      0      0    4.840769        C
...          ...     ...     ...    ...    ...         ...      ...
999995         0       2    male      0      0   26.196512        S
999996         1       1  female      0      0  102.555248        S
999997         0       3    male      1      0    8.274807        S
999998         0       2    male      1      0    0.000000        S
999999         1       1  female      1      0   57.720316        S

[1000000 rows x 7 columns]

In [7]:
data['Embarked'].mode()

0    S
Name: Embarked, dtype: str

In [8]:
data['Embarked']=data['Embarked'].replace({'S':'Southamton','C':'Cheboung','Q':'Queensland'})

In [9]:
data.dropna(subset=['Embarked'], inplace=True)

In [10]:
label=LabelEncoder() 
onehot=OneHotEncoder()
scale=StandardScaler()

In [13]:
data.sample()

        Survived  Pclass  Sex  SibSp  Parch        Fare  Embarked
366484         1       1    0      1      0  104.646726  Cheboung

In [12]:
data['Sex']=label.fit_transform(data['Sex'])