In [1]:
9+9

18

In [14]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd

In [15]:
with open('label_encoder.pkl', 'rb') as file:
    label=pickle.load(file)
with open('onehot_encoder.pkl', 'rb') as file:
    ohe=pickle.load(file)
with open('scale.pkl', 'rb') as file:
    scale=pickle.load(file)

In [16]:
model = load_model('model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [17]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 128)            │         1,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,523 (45.02 KB)

 Trainable params: 11,521 (45.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

In [18]:
user={'Pclass':1,'Sex':'male','SibSp':2,'Parch':1,'Fare':76,'Embarked':'Cheboung'}

In [19]:
user = pd.DataFrame([user])

In [20]:
user

   Pclass   Sex  SibSp  Parch  Fare  Embarked
0       1  male      2      1    76  Cheboung

In [21]:
user['Sex']=label.transform(user['Sex'])

In [24]:
embarked=ohe.transform(user[['Embarked']])

In [25]:
embarked=pd.DataFrame(embarked, columns=ohe.get_feature_names_out())

In [26]:
user=pd.concat([user.drop(columns=['Embarked']),embarked],axis=1)

In [27]:
user

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cheboung,Embarked_Queensland,Embarked_Southamtom
0,1,1,2,1,76,1.0,0.0,0.0

In [28]:
user[['Pclass','SibSp','Parch','Fare']]=scale.transform(user[['Pclass','SibSp','Parch','Fare']])

In [29]:
user

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cheboung,Embarked_Queensland,Embarked_Southamtom
0,-1.568865,1,1.347567,0.833802,0.886456,1.0,0.0,0.0

In [30]:
y=model.predict(user)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 591ms/step

In [31]:
y

array([[0.69735223]], dtype=float32)

In [32]:
y[0][0]

np.float32(0.69735223)

In [33]:
if y > 0.5:
    print('survive')
else:
    print('not')

survive