In [1]:
8+7

15

In [2]:
import pandas as pd

In [3]:
data=pd.read_csv('ai_dev_productivity.csv')

In [4]:
data.shape

(500, 9)

In [5]:
data.head()

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,cognitive_load,task_success
0,5.99,600,1,5.8,2,1,0.71,5.4,1
1,4.72,568,2,6.9,5,3,1.75,4.7,1
2,6.30,560,1,8.9,2,0,2.27,2.2,1
3,8.05,600,7,6.3,9,5,1.40,5.9,0
4,4.53,421,6,6.9,4,0,1.26,6.3,1

In [6]:
data.isnull().sum()

hours_coding        0
coffee_intake_mg    0
distractions        0
sleep_hours         0
commits             0
bugs_reported       0
ai_usage_hours      0
cognitive_load      0
task_success        0
dtype: int64

In [7]:
data.duplicated().sum()

np.int64(0)

In [8]:
data.describe()

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,cognitive_load,task_success
count,500.000000,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000,500.000000,500.000000
mean,5.015600,463.192000,2.976000,6.975800,4.60800,0.858000,1.510920,4.498200,0.606000
std,1.947253,142.334991,1.678409,1.455965,2.70499,1.102846,1.085557,1.868861,0.489124
min,0.000000,6.000000,0.000000,3.000000,0.00000,0.000000,0.000000,1.000000,0.000000
25%,3.600000,369.500000,2.000000,6.100000,3.00000,0.000000,0.697500,3.175000,0.000000
50%,5.030000,500.500000,3.000000,6.950000,5.00000,0.000000,1.260000,4.400000,1.000000
75%,6.275000,600.000000,4.000000,7.900000,6.00000,2.000000,2.070000,5.800000,1.000000
max,12.000000,600.000000,8.000000,10.000000,13.00000,5.000000,6.360000,10.000000,1.000000

In [9]:
data.sample()

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,cognitive_load,task_success
334,6.95,600,1,6.7,7,0,3.06,2.6,1

In [10]:
from sklearn.preprocessing import StandardScaler
scale=StandardScaler()

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X=data.drop(columns=['cognitive_load'])

In [13]:
Y=data['cognitive_load']

In [14]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [15]:
X_train.shape

(400, 8)

In [16]:
X_train

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,task_success
249,5.81,511,1,9.4,5,0,1.52,1
433,6.44,534,5,6.3,1,0,2.14,1
19,2.18,255,3,3.7,3,0,0.64,0
322,3.36,451,3,6.2,2,3,1.99,0
332,5.15,465,5,5.9,3,0,1.96,0
...,...,...,...,...,...,...,...,...
106,8.77,600,2,7.5,5,0,1.02,1
270,7.88,600,7,8.8,8,0,1.51,1
348,3.56,324,2,6.1,4,2,0.19,0
435,5.15,490,2,8.7,8,0,1.14,1
102,4.31,475,1,5.5,3,0,1.07,1

In [17]:
data.sample()

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,cognitive_load,task_success
314,7.61,600,3,6.1,8,1,3.4,5.4,1

In [18]:
X.columns

Index(['hours_coding', 'coffee_intake_mg', 'distractions', 'sleep_hours',
       'commits', 'bugs_reported', 'ai_usage_hours', 'task_success'],
      dtype='str')

In [19]:
X_train[['hours_coding', 'coffee_intake_mg', 'distractions', 'sleep_hours','commits', 'bugs_reported', 'ai_usage_hours']]=scale.fit_transform(X_train[['hours_coding', 'coffee_intake_mg', 'distractions', 'sleep_hours','commits', 'bugs_reported', 'ai_usage_hours']])
X_test[['hours_coding', 'coffee_intake_mg', 'distractions', 'sleep_hours','commits', 'bugs_reported', 'ai_usage_hours']]=scale.fit_transform(X_test[['hours_coding', 'coffee_intake_mg', 'distractions', 'sleep_hours','commits', 'bugs_reported', 'ai_usage_hours']])

In [20]:
X_train

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,task_success
249,0.410116,0.348814,-1.159772,1.628183,0.146206,-0.780969,0.050837,1
433,0.731716,0.508152,1.222301,-0.459879,-1.334364,-0.780969,0.634796,1
19,-1.442912,-1.424697,0.031265,-2.211156,-0.594079,-0.780969,-0.778007,0
322,-0.840550,-0.066853,0.031265,-0.527236,-0.964221,1.927593,0.493516,0
332,0.073202,0.030136,1.222301,-0.729306,-0.594079,-0.780969,0.465260,0
...,...,...,...,...,...,...,...,...
106,1.921126,0.965386,-0.564254,0.348403,0.146206,-0.780969,-0.420097,1
270,1.466802,0.965386,2.413338,1.224042,1.256634,-0.780969,0.041419,1
348,-0.738455,-0.946681,-0.564254,-0.594592,-0.223936,1.024739,-1.201848,0
435,0.073202,0.203330,-0.564254,1.156685,1.256634,-0.780969,-0.307073,1
102,-0.355598,0.099414,-1.159772,-0.998733,-0.594079,-0.780969,-0.373004,1

In [21]:
X_test

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,task_success
361,1.597639,0.954021,-0.054155,-1.769622,0.879938,0.157766,2.799184,0
73,1.629397,0.954021,-0.655877,-0.940583,1.619381,-0.770271,-0.000433,1
374,2.253971,0.954021,-1.257599,-0.563747,1.619381,-0.770271,0.424276,1
155,-0.784211,-0.853978,-0.054155,0.642129,0.140494,0.157766,-0.381805,0
104,-0.196688,0.110288,-0.655877,-0.036176,1.619381,1.085803,-0.303797,1
...,...,...,...,...,...,...,...,...
347,-1.514645,-0.997111,-0.655877,1.697270,-0.598949,-0.770271,-1.075209,0
86,0.941307,0.954021,-0.655877,-1.091317,-0.229227,1.085803,-1.049206,1
75,0.840740,0.607487,-1.257599,-1.015950,0.140494,-0.770271,0.770978,1
438,-1.832225,-2.270243,0.547567,0.265293,-1.338393,-0.770271,-1.109879,0
15,-0.620128,-0.364312,-0.054155,-1.317419,0.510216,-0.770271,-0.971199,0

In [22]:
(X_train.shape[1],)

(8,)

In [23]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [24]:
model = Sequential([Dense(64,input_shape=(X_train.shape[1],)), Dense(1,activation='linear')])

c:\Users\a810557\akash\LangchainUpdated\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [25]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 641 (2.50 KB)

 Trainable params: 641 (2.50 KB)

 Non-trainable params: 0 (0.00 B)

In [27]:
model.compile(optimizer='adam',metrics=['mae'], loss='mse')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [29]:
model.fit(X_train,Y_train, epochs=30)

Epoch 1/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 3.3839 - mae: 1.4843
Epoch 2/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.9065 - mae: 1.3614
Epoch 3/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.5681 - mae: 1.2703
Epoch 4/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.3884 - mae: 1.2263
Epoch 5/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.2590 - mae: 1.1954
Epoch 6/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.1703 - mae: 1.1748
Epoch 7/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.1081 - mae: 1.1602
Epoch 8/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.0651 - mae: 1.1524
Epoch 9/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.0306 - mae: 1.1459
Epoch 10/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.9815 - mae: 1.1334
Epoch 11/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.9413 - mae: 1.1214
Epoch 12/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.9057 - mae: 1.1112
Epoch 13/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.8698 - mae: 1.1013
Epoch 14/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.8290 - mae: 1.0890
Epoch 15/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.7917 - mae: 1.0786
Epoch 16/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.7581 - mae: 1.0698
Epoch 17/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.7217 - mae: 1.0597
Epoch 18/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.6967 - mae: 1.0530
Epoch 19/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.6524 - mae: 1.0392
Epoch 20/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.6238 - mae: 1.0284
Epoch 21/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.5826 - mae: 1.0158
Epoch 22/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.5551 - mae: 1.0065
Epoch 23/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.5199 - mae: 0.9959
Epoch 24/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.4894 - mae: 0.9851
Epoch 25/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.4623 - mae: 0.9752
Epoch 26/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.4322 - mae: 0.9665
Epoch 27/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.4079 - mae: 0.9576
Epoch 28/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.3870 - mae: 0.9484
Epoch 29/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.3561 - mae: 0.9407
Epoch 30/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.3253 - mae: 0.9273

In [30]:
from sklearn.metrics import mean_squared_error

In [31]:
Y_predict=model.predict(X_test)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

In [33]:
mean_squared_error(Y_predict,Y_test)

1.2115123533523837