In [1]:
9+9

18

In [20]:
import pandas as pd

In [21]:
data=pd.read_csv('twitter_training.csv')

In [22]:
data=data.sample(10000,random_state=42)

In [23]:
data.shape

(10000, 4)

In [24]:
data.head()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
34877,6792,Fortnite,Irrelevant,went to go in george's room to find his door w...
21704,4115,CS-GO,Positive,Yo this looks LIT! Team:GO/Overwatch combo
47008,5665,HomeDepot,Negative,Pay attention executive administrators. While ...
7969,9369,Overwatch,Irrelevant,Guy looked at me and says my name was put on t...
454,2476,Borderlands,Positive,one

In [25]:
data

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
34877,6792,Fortnite,Irrelevant,went to go in george's room to find his door w...
21704,4115,CS-GO,Positive,Yo this looks LIT! Team:GO/Overwatch combo
47008,5665,HomeDepot,Negative,Pay attention executive administrators. While ...
7969,9369,Overwatch,Irrelevant,Guy looked at me and says my name was put on t...
454,2476,Borderlands,Positive,one
...,...,...,...,...
5763,191,Amazon,Neutral,@OtakuWeeb11 Thanks for entering Grand Summone...
6213,269,Amazon,Positive,Couldn't agree some more. It'S s excellent.
12347,8523,NBA2K,Negative,Soooo no token market update for the rest of t...
2515,1639,CallOfDutyBlackopsColdWar,Positive,"For anyone jumping into this Beta weekend, I h..."
57264,11423,TomClancysRainbowSix,Neutral,Week 1. Perfection MTG.. ---------------------...

In [26]:
data.isnull().sum()

2401                                                       0
Borderlands                                                0
Positive                                                   0
im getting on borderlands and i will murder you all ,    101
dtype: int64

In [27]:
data.duplicated().sum()

np.int64(56)

In [28]:
data.sample()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
63424,7670,MaddenNFL,Negative,Scott Walker at 86?? Smh kill them this year @...

In [29]:
data=data.dropna()

In [30]:
data.drop(columns=['2401','Borderlands'],inplace=True)

In [31]:
data.sample()

      Positive im getting on borderlands and i will murder you all ,
1859  Positive  Had some network issues but I'm back and were ...

In [32]:
data.rename(columns={'Positive':'Sentiment','im getting on borderlands and i will murder you all ,':'Tweets'},inplace=True)

In [34]:
data.sample()

      Sentiment                                             Tweets
56992  Negative  Sup<unk> @Rainbow6Game. Me and my Friends have...

In [35]:
data=data[(data['Sentiment']=='Positive')|(data['Sentiment']=='Negative')|(data['Sentiment']=='Neutral')]

In [36]:
data.sample()

      Sentiment                               Tweets
69538  Positive  Now this is a poggers item. :<unk>0

In [37]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()

In [38]:
data['Sentiment']=label.fit_transform(data['Sentiment'])

In [39]:
import tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer

In [40]:
tokenizer=Tokenizer(oov_token='Nothing')

In [41]:
tokenizer.fit_on_texts(data['Tweets'])

In [42]:
tokenizer.word_index

{'Nothing': 1,
 'the': 2,
 'i': 3,
 'to': 4,
 'and': 5,
 'a': 6,
 'of': 7,
 'is': 8,
 'in': 9,
 'for': 10,
 'it': 11,
 'this': 12,
 'my': 13,
 'on': 14,
 'you': 15,
 'that': 16,
 'com': 17,
 'game': 18,
 'with': 19,
 'so': 20,
 'have': 21,
 'me': 22,
 'be': 23,
 'just': 24,
 'not': 25,
 'was': 26,
 'but': 27,
 'are': 28,
 'all': 29,
 'at': 30,
 '2': 31,
 'out': 32,
 'pic': 33,
 'get': 34,
 'twitter': 35,
 'your': 36,
 'like': 37,
 'from': 38,
 'now': 39,
 'as': 40,
 'we': 41,
 'play': 42,
 'good': 43,
 'johnson': 44,
 't': 45,
 'they': 46,
 'if': 47,
 'new': 48,
 'do': 49,
 'about': 50,
 'can': 51,
 'has': 52,
 'one': 53,
 'when': 54,
 'no': 55,
 'will': 56,
 'time': 57,
 'really': 58,
 'more': 59,
 'an': 60,
 "i'm": 61,
 'love': 62,
 'unk': 63,
 'people': 64,
 'up': 65,
 'what': 66,
 'some': 67,
 '3': 68,
 'been': 69,
 'still': 70,
 'shit': 71,
 'co': 72,
 'by': 73,
 "it's": 74,
 'why': 75,
 '’': 76,
 'or': 77,
 'how': 78,
 'amazon': 79,
 'microsoft': 80,
 'https': 81,
 'games': 82,
 'best': 83,
 'playing': 84,
 'facebook': 85,
 'because': 86,
 'dead': 87,
 'xbox': 88,
 'great': 89,
 'verizon': 90,
 '1': 91,
 'fucking': 92,
 'got': 93,
 'even': 94,
 'fuck': 95,
 'back': 96,
 'who': 97,
 'see': 98,
 'go': 99,
 'red': 100,
 'rhandlerr': 101,
 'there': 102,
 'home': 103,
 '5': 104,
 'much': 105,
 'us': 106,
 'had': 107,
 'please': 108,
 'going': 109,
 'them': 110,
 'google': 111,
 's': 112,
 'only': 113,
 "can't": 114,
 'borderlands': 115,
 'nvidia': 116,
 'fix': 117,
 'am': 118,
 'day': 119,
 'after': 120,
 'would': 121,
 'tv': 122,
 'its': 123,
 'their': 124,
 'fun': 125,
 'eamaddennfl': 126,
 'today': 127,
 'first': 128,
 'again': 129,
 '4': 130,
 'than': 131,
 'bad': 132,
 'fifa': 133,
 'over': 134,
 '2020': 135,
 'these': 136,
 'most': 137,
 'our': 138,
 'pubg': 139,
 '…': 140,
 'very': 141,
 'wait': 142,
 'make': 143,
 'never': 144,
 'also': 145,
 'here': 146,
 'then': 147,
 'thank': 148,
 'nba2k': 149,
 'twitch': 150,
 'every': 151,
 'played': 152,
 'redemption': 153,
 'damn': 154,
 'rainbow6game': 155,
 'work': 156,
 'think': 157,
 "don't": 158,
 'ps5': 159,
 'i’m': 160,
 'know': 161,
 'he': 162,
 'thanks': 163,
 'gta': 164,
 'amazing': 165,
 'ever': 166,
 'news': 167,
 'want': 168,
 'too': 169,
 'call': 170,
 'video': 171,
 'x': 172,
 'legends': 173,
 'depot': 174,
 'year': 175,
 'last': 176,
 'getting': 177,
 "i've": 178,
 'series': 179,
 'v': 180,
 'well': 181,
 'any': 182,
 'watch': 183,
 'happy': 184,
 'say': 185,
 '10': 186,
 'overwatch': 187,
 'league': 188,
 'into': 189,
 'guys': 190,
 'battlefield': 191,
 'update': 192,
 'world': 193,
 'help': 194,
 'another': 195,
 'while': 196,
 'years': 197,
 'man': 198,
 'u': 199,
 'ass': 200,
 'looks': 201,
 'creed': 202,
 'store': 203,
 'money': 204,
 'warcraft': 205,
 'youtube': 206,
 'youtu': 207,
 'off': 208,
 'need': 209,
 'big': 210,
 'black': 211,
 'right': 212,
 'did': 213,
 'live': 214,
 'win': 215,
 'down': 216,
 'fortnite': 217,
 'many': 218,
 'ghostrecon': 219,
 'being': 220,
 'his': 221,
 'should': 222,
 'team': 223,
 'always': 224,
 'finally': 225,
 'take': 226,
 'actually': 227,
 'already': 228,
 'next': 229,
 'players': 230,
 'free': 231,
 'pc': 232,
 'via': 233,
 'look': 234,
 'made': 235,
 'thing': 236,
 'duty': 237,
 'awesome': 238,
 'support': 239,
 'way': 240,
 'come': 241,
 'everyone': 242,
 'hearthstone': 243,
 'better': 244,
 'nice': 245,
 'which': 246,
 'it’s': 247,
 'something': 248,
 'wtf': 249,
 'such': 250,
 'health': 251,
 'buy': 252,
 'could': 253,
 'since': 254,
 'care': 255,
 'before': 256,
 'stop': 257,
 'done': 258,
 'other': 259,
 '20': 260,
 'playstation': 261,
 'online': 262,
 'access': 263,
 'playapex': 264,
 'wow': 265,
 'oh': 266,
 'were': 267,
 'ubisoft': 268,
 'days': 269,
 'gonna': 270,
 'ly': 271,
 'bit': 272,
 'her': 273,
 'baby': 274,
 'account': 275,
 'looking': 276,
 'keep': 277,
 'excited': 278,
 'hate': 279,
 'mobile': 280,
 'long': 281,
 'csgo': 282,
 'same': 283,
 'having': 284,
 'give': 285,
 'stream': 286,
 'trying': 287,
 'lot': 288,
 'start': 289,
 'cool': 290,
 'old': 291,
 'card': 292,
 'hey': 293,
 'everything': 294,
 'player': 295,
 '100': 296,
 '6': 297,
 'working': 298,
 'war': 299,
 'someone': 300,
 'where': 301,
 'cyberpunk': 302,
 'nothing': 303,
 'pretty': 304,
 'check': 305,
 'doing': 306,
 'life': 307,
 'through': 308,
 '7': 309,
 'absolutely': 310,
 'god': 311,
 'powder': 312,
 'him': 313,
 'top': 314,
 'service': 315,
 'phone': 316,
 'pay': 317,
 'lol': 318,
 'probably': 319,
 'company': 320,
 'those': 321,
 'm': 322,
 'super': 323,
 'use': 324,
 'night': 325,
 'dont': 326,
 'things': 327,
 'im': 328,
 'dota': 329,
 'does': 330,
 'can’t': 331,
 'hell': 332,
 'servers': 333,
 'hope': 334,
 'stupid': 335,
 'feel': 336,
 'times': 337,
 'season': 338,
 'real': 339,
 'uk': 340,
 'makes': 341,
 'yet': 342,
 'let': 343,
 "doesn't": 344,
 '2077': 345,
 'little': 346,
 'week': 347,
 'miss': 348,
 'worst': 349,
 'both': 350,
 'until': 351,
 'open': 352,
 'almost': 353,
 'won': 354,
 'chance': 355,
 'without': 356,
 'making': 357,
 'hours': 358,
 'story': 359,
 'problem': 360,
 'two': 361,
 'hard': 362,
 'apex': 363,
 'release': 364,
 'cant': 365,
 'literally': 366,
 'try': 367,
 'anyone': 368,
 'said': 369,
 'favorite': 370,
 'sure': 371,
 'own': 372,
 'show': 373,
 'find': 374,
 'against': 375,
 '0': 376,
 '19': 377,
 'full': 378,
 'minutes': 379,
 'tell': 380,
 'lost': 381,
 'assassins': 382,
 'console': 383,
 'tt': 384,
 'app': 385,
 'gets': 386,
 'business': 387,
 'stuff': 388,
 'gaming': 389,
 'few': 390,
 '21': 391,
 'fact': 392,
 'pro': 393,
 'cold': 394,
 'trash': 395,
 'ea': 396,
 'soon': 397,
 "that's": 398,
 'vaccine': 399,
 'using': 400,
 'tonight': 401,
 'far': 402,
 'idea': 403,
 "y'all": 404,
 'callofduty': 405,
 'coming': 406,
 'part': 407,
 'says': 408,
 'mode': 409,
 'dota2': 410,
 'gameplay': 411,
 'ops': 412,
 'beluba': 413,
 'covid': 414,
 'beautiful': 415,
 'perfect': 416,
 'ranked': 417,
 'hit': 418,
 'around': 419,
 'went': 420,
 'ban': 421,
 'weekend': 422,
 'crazy': 423,
 'thought': 424,
 'wrong': 425,
 'friends': 426,
 'end': 427,
 'share': 428,
 'enjoy': 429,
 'anything': 430,
 'screen': 431,
 'whole': 432,
 "you're": 433,
 'used': 434,
 'y’all': 435,
 'madden': 436,
 'tried': 437,
 'though': 438,
 'million': 439,
 'ift': 440,
 "assassin's": 441,
 'away': 442,
 'due': 443,
 'job': 444,
 'watching': 445,
 'forward': 446,
 'order': 447,
 'put': 448,
 'interesting': 449,
 'exciting': 450,
 '2k': 451,
 'talc': 452,
 '”': 453,
 "didn't": 454,
 'high': 455,
 'grand': 456,
 'currently': 457,
 'change': 458,
 'sad': 459,
 '30': 460,
 'system': 461,
 'cs': 462,
 'bought': 463,
 'price': 464,
 'ps4': 465,
 'data': 466,
 'guy': 467,
 '15': 468,
 'p': 469,
 'd': 470,
 'graphics': 471,
 'playhearthstone': 472,
 'month': 473,
 'line': 474,
 "i'll": 475,
 'customer': 476,
 'level': 477,
 'apps': 478,
 'sorry': 479,
 'maybe': 480,
 'morning': 481,
 'windows': 482,
 'definitely': 483,
 'took': 484,
 'worth': 485,
 'epic': 486,
 'second': 487,
 'kill': 488,
 'during': 489,
 'able': 490,
 'latest': 491,
 'server': 492,
 '12': 493,
 'wanted': 494,
 'services': 495,
 'skin': 496,
 'character': 497,
 'reason': 498,
 'selling': 499,
 'came': 500,
 'point': 501,
 'i’ve': 502,
 'banned': 503,
 'rewards': 504,
 'don’t': 505,
 'ok': 506,
 'problems': 507,
 'finished': 508,
 'single': 509,
 'read': 510,
 'n2k': 511,
 'might': 512,
 "haven't": 513,
 'pre': 514,
 'despite': 515,
 'myteam': 516,
 'post': 517,
 'design': 518,
 'based': 519,
 'bro': 520,
 'enough': 521,
 'power': 522,
 'else': 523,
 'set': 524,
 'internet': 525,
 'run': 526,
 'gen': 527,
 'net': 528,
 'homedepot': 529,
 'broken': 530,
 'killed': 531,
 'tomorrow': 532,
 'half': 533,
 'annoying': 534,
 'may': 535,
 'instead': 536,
 'w': 537,
 'mean': 538,
 'updates': 539,
 'org': 540,
 'eu': 541,
 'luck': 542,
 '8': 543,
 'ago': 544,
 'hour': 545,
 'content': 546,
 'saying': 547,
 'terrible': 548,
 'list': 549,
 'guess': 550,
 'ronnie2k': 551,
 'seems': 552,
 'person': 553,
 'feels': 554,
 'taken': 555,
 'don': 556,
 'teams': 557,
 'different': 558,
 'cards': 559,
 'music': 560,
 'breakpoint': 561,
 'trailer': 562,
 'blizzard': 563,
 'experience': 564,
 'wanna': 565,
 'later': 566,
 'comes': 567,
 'leagueoflegends': 568,
 'e': 569,
 'late': 570,
 'shot': 571,
 'huge': 572,
 'must': 573,
 'believe': 574,
 'face': 575,
 'hear': 576,
 'needs': 577,
 'she': 578,
 'yall': 579,
 'funny': 580,
 'match': 581,
 'warzone': 582,
 "won't": 583,
 'yo': 584,
 'holy': 585,
 'major': 586,
 'myself': 587,
 'completely': 588,
 'cod': 589,
 'seen': 590,
 'products': 591,
 'name': 592,
 'iphone': 593,
 'patch': 594,
 '“': 595,
 'sucks': 596,
 'early': 597,
 'least': 598,
 'gone': 599,
 'r': 600,
 'sometimes': 601,
 'seriously': 602,
 'proud': 603,
 'anymore': 604,
 'ready': 605,
 'together': 606,
 'cause': 607,
 'worse': 608,
 'totally': 609,
 'gold': 610,
 'review': 611,
 'smh': 612,
 'suck': 613,
 'started': 614,
 'event': 615,
 'die': 616,
 'months': 617,
 'living': 618,
 'below': 619,
 'drop': 620,
 'sound': 621,
 'pass': 622,
 'loved': 623,
 'hello': 624,
 'y': 625,
 'achievement': 626,
 'garbage': 627,
 'movie': 628,
 '3080': 629,
 'yes': 630,
 'fan': 631,
 'stay': 632,
 'step': 633,
 'apple': 634,
 'seeing': 635,
 'error': 636,
 'leave': 637,
 'complete': 638,
 'three': 639,
 're': 640,
 '9': 641,
 'edition': 642,
 've': 643,
 'gift': 644,
 'number': 645,
 'under': 646,
 'bugs': 647,
 'community': 648,
 'girl': 649,
 'lmao': 650,
 'fps': 651,
 'dlvr': 652,
 'friend': 653,
 'running': 654,
 'keeps': 655,
 'add': 656,
 'join': 657,
 'bring': 658,
 'mind': 659,
 'code': 660,
 'moment': 661,
 'understand': 662,
 'launch': 663,
 'switch': 664,
 'sick': 665,
 'city': 666,
 'canada': 667,
 'weeks': 668,
 'book': 669,
 'class': 670,
 'thinking': 671,
 'truly': 672,
 'found': 673,
 'yesterday': 674,
 'india': 675,
 'birthday': 676,
 'honestly': 677,
 'continue': 678,
 'market': 679,
 'rtx': 680,
 'hi': 681,
 'streaming': 682,
 'omg': 683,
 'received': 684,
 'retweet': 685,
 'easports': 686,
 'issues': 687,
 'means': 688,
 'remember': 689,
 "they're": 690,
 'family': 691,
 'ghost': 692,
 'sold': 693,
 'earned': 694,
 'c': 695,
 'technology': 696,
 'playoverwatch': 697,
 'yeah': 698,
 'incredible': 699,
 'bullshit': 700,
 'users': 701,
 'taking': 702,
 'mad': 703,
 'tho': 704,
 'house': 705,
 'id': 706,
 'follow': 707,
 'plz': 708,
 'released': 709,
 'en': 710,
 'insane': 711,
 'global': 712,
 'talk': 713,
 'bug': 714,
 'trust': 715,
 'quite': 716,
 'warfare': 717,
 'issue': 718,
 'main': 719,
 'trump': 720,
 'daily': 721,
 'listen': 722,
 '–': 723,
 'battle': 724,
 'that’s': 725,
 'kills': 726,
 'small': 727,
 'waiting': 728,
 'place': 729,
 'past': 730,
 'easy': 731,
 'cannot': 732,
 'action': 733,
 'instagram': 734,
 'buying': 735,
 'spent': 736,
 'tired': 737,
 'channel': 738,
 'tech': 739,
 'decision': 740,
 'commission': 741,
 'hot': 742,
 "what's": 743,
 'once': 744,
 'coronavirus': 745,
 'joke': 746,
 'lots': 747,
 'men': 748,
 'article': 749,
 'ur': 750,
 'steam': 751,
 'move': 752,
 'link': 753,
 'left': 754,
 'each': 755,
 'wild': 756,
 'either': 757,
 'videos': 758,
 'worked': 759,
 '11': 760,
 'saw': 761,
 'original': 762,
 'l': 763,
 'search': 764,
 'b': 765,
 'women': 766,
 'paid': 767,
 'died': 768,
 'goes': 769,
 'knows': 770,
 'called': 771,
 'turn': 772,
 'points': 773,
 'glad': 774,
 "there's": 775,
 'deal': 776,
 'rockstargames': 777,
 'sales': 778,
 'cute': 779,
 'wins': 780,
 'digital': 781,
 'death': 782,
 'f': 783,
 'bitch': 784,
 'ubisoftsupport': 785,
 "let's": 786,
 'hyped': 787,
 'favourite': 788,
 'including': 789,
 'close': 790,
 'gotta': 791,
 'head': 792,
 'dope': 793,
 'okay': 794,
 'sense': 795,
 'congratulations': 796,
 'o': 797,
 'boy': 798,
 'redeeming': 799,
 'delayed': 800,
 'special': 801,
 'item': 802,
 'hold': 803,
 'break': 804,
 'slow': 805,
 'box': 806,
 'version': 807,
 'page': 808,
 'option': 809,
 'summoners': 810,
 'unit': 811,
 'ridiculous': 812,
 'n': 813,
 'developers': 814,
 'franchise': 815,
 'sell': 816,
 'ai': 817,
 '14': 818,
 'stuck': 819,
 'dear': 820,
 'af': 821,
 'true': 822,
 'crap': 823,
 'fast': 824,
 'history': 825,
 'enjoying': 826,
 'cancer': 827,
 'kind': 828,
 'sony': 829,
 'talking': 830,
 'plays': 831,
 'spend': 832,
 'fans': 833,
 'chinese': 834,
 'connection': 835,
 'social': 836,
 'fortnitegame': 837,
 'less': 838,
 'forever': 839,
 'kinda': 840,
 'welcome': 841,
 'valorant': 842,
 'plan': 843,
 '60': 844,
 'safe': 845,
 'stock': 846,
 'nfl': 847,
 'nba': 848,
 'star': 849,
 'poverty': 850,
 'sounds': 851,
 'edge': 852,
 'date': 853,
 'learning': 854,
 'calling': 855,
 '13': 856,
 'moments': 857,
 'decided': 858,
 'ball': 859,
 'plus': 860,
 'drive': 861,
 "isn't": 862,
 'enjoyed': 863,
 'takes': 864,
 'powerful': 865,
 "we're": 866,
 'absolute': 867,
 'test': 868,
 'log': 869,
 'wish': 870,
 'works': 871,
 'shooting': 872,
 'kids': 873,
 'felt': 874,
 'selected': 875,
 'siege': 876,
 'fake': 877,
 'current': 878,
 'email': 879,
 'art': 880,
 'state': 881,
 'gpu': 882,
 'modern': 883,
 'football': 884,
 'shut': 885,
 'word': 886,
 'demon': 887,
 'odyssey': 888,
 'matter': 889,
 'longer': 890,
 'sea': 891,
 'performance': 892,
 'trial': 893,
 'beta': 894,
 'especially': 895,
 'companies': 896,
 '09': 897,
 'lose': 898,
 'website': 899,
 'bc': 900,
 'rest': 901,
 'white': 902,
 'couple': 903,
 'final': 904,
 'future': 905,
 'sent': 906,
 'heard': 907,
 'eahelp': 908,
 'school': 909,
 '2016': 910,
 'dark': 911,
 'yourself': 912,
 'walmart': 913,
 'shitty': 914,
 'car': 915,
 'theft': 916,
 'ahead': 917,
 'j': 918,
 'controller': 919,
 '16': 920,
 'cry': 921,
 'anywhere': 922,
 'short': 923,
 'happens': 924,
 'created': 925,
 'features': 926,
 'geforce': 927,
 'fight': 928,
 'sweet': 929,
 'ask': 930,
 'added': 931,
 'quit': 932,
 'poor': 933,
 'voice': 934,
 'fantastic': 935,
 'program': 936,
 'government': 937,
 'china': 938,
 '70': 939,
 'report': 940,
 'defense': 941,
 'security': 942,
 'crashes': 943,
 'golden': 944,
 'hero': 945,
 'mut': 946,
 'between': 947,
 'decent': 948,
 'wonder': 949,
 'copy': 950,
 'behind': 951,
 'quality': 952,
 '25': 953,
 'pandemic': 954,
 'winning': 955,
 'cross': 956,
 'till': 957,
 'fixed': 958,
 'massive': 959,
 'awful': 960,
 'quiz': 961,
 'feeling': 962,
 'told': 963,
 'fire': 964,
 'quick': 965,
 'wikipedia': 966,
 '24': 967,
 'fall': 968,
 'lately': 969,
 'turned': 970,
 'greatest': 971,
 'ios': 972,
 'within': 973,
 'hacked': 974,
 'packs': 975,
 'brand': 976,
 'happened': 977,
 'stops': 978,
 'suddenly': 979,
 'platform': 980,
 'loading': 981,
 'heart': 982,
 '50': 983,
 'toxic': 984,
 'offer': 985,
 'boring': 986,
 'pick': 987,
 'inside': 988,
 'gs': 989,
 'dog': 990,
 'towards': 991,
 'press': 992,
 'buff': 993,
 'low': 994,
 'hunter': 995,
 'didn’t': 996,
 'calls': 997,
 'shows': 998,
 'workers': 999,
 'imo': 1000,
 ...}

In [43]:
tokenizer.word_counts

OrderedDict([('yo', 35),
             ('this', 1572),
             ('looks', 119),
             ('lit', 12),
             ('team', 110),
             ('go', 229),
             ('overwatch', 132),
             ('combo', 7),
             ('pay', 71),
             ('attention', 8),
             ('executive', 4),
             ('administrators', 3),
             ('while', 125),
             ('your', 483),
             ('stores', 17),
             ('are', 631),
             ('taking', 27),
             ('delivery', 16),
             ('orders', 15),
             ('for', 1710),
             ('pallets', 2),
             ('of', 2135),
             ('bricks', 2),
             ('to', 3209),
             ('downtown', 2),
             ('then', 162),
             ('you', 1289),
             ('were', 89),
             ('being', 112),
             ('used', 50),
             ('in', 1747),
             ('helping', 16),
             ('the', 4882),
             ('destruction', 5),
             ('private', 8),
             ('property', 4),
             ('one', 365),
             ('rainbow6game', 153),
             ('server', 43),
             ('available', 14),
             ('xbox', 248),
             ('🥺', 6),
             ('so', 841),
             ('awesome', 104),
             ('siege', 21),
             ('attempt', 5),
             ('strangest', 3),
             ('bleeding', 4),
             ('out', 497),
             ('spinning', 7),
             ('sequence', 2),
             ('ever', 148),
             ('s', 207),
             ('my', 1357),
             ('first', 179),
             ('squadmate', 1),
             ('john', 10),
             ('could', 98),
             ('see', 231),
             ('exactly', 10),
             ('which', 100),
             ('was', 633),
             ("i'm", 342),
             ('really', 354),
             ('looking', 86),
             ('forward', 49),
             ('game', 995),
             ('verizon', 245),
             ('sheds', 1),
             ('81', 3),
             ('000', 14),
             ('digital', 24),
             ('tv', 185),
             ('on', 1319),
             ('black', 114),
             ('cutting', 6),
             ('escalates', 1),
             ('breitbart', 2),
             ('com', 1095),
             ('entertainment', 10),
             ('internet', 40),
             ('gave', 14),
             ('way', 103),
             ('coke', 1),
             ('show', 60),
             ('money', 116),
             ('keep', 86),
             ('ch', 2),
             ('tmmobile', 1),
             ('guys', 128),
             ('very', 170),
             ('slow', 23),
             ('town', 9),
             ('tuba', 1),
             ('fix', 198),
             ('fucking', 240),
             ('pro', 56),
             ('am', 198),
             ('can’t', 68),
             ('find', 60),
             ('no', 360),
             ('games', 268),
             ('2ksupport', 16),
             ('i', 3287),
             ('love', 338),
             ('how', 287),
             ('gives', 17),
             ('each', 25),
             ('a', 2631),
             ('new', 386),
             ('loot', 15),
             ('box', 23),
             ('playing', 260),
             ('support', 104),
             ('forgot', 17),
             ('when', 365),
             ('hated', 4),
             ('who', 232),
             ('mad', 27),
             ('about', 379),
             ('dame', 9),
             ('getting', 142),
             ('itself', 13),
             ('regular', 7),
             ('cover', 10),
             ('like', 478),
             ('kobe', 7),
             ('or', 290),
             ('get', 486),
             ('its', 185),
             ('legend', 15),
             ('edition', 31),
             ('unk', 337),
             ('disrespect', 7),
             ('y’all', 50),
             ('showed', 14),
             ('wild', 25),
             ('simpletons', 1),
             ('only', 206),
             ('lol', 71),
             ("here's", 9),
             ('montage', 4),
             ('rescuing', 1),
             ('teammate', 10),
             ('spreadlovehxly', 2),
             ('few', 57),
             ('times', 67),
             ('other', 96),
             ('day', 195),
             ('they', 403),
             ('will', 355),
             ('forever', 22),
             ('be', 741),
             ('heart', 18),
             ('but', 633),
             ('do', 380),
             ('kinda', 22),
             ('tho', 27),
             ('5', 216),
             ('friends', 51),
             ('players', 107),
             ('pokemon', 9),
             ('borderlands', 204),
             ('p', 46),
             ('much', 215),
             ('all', 626),
             ('sims', 2),
             ('6', 78),
             ("haven't", 41),
             ('played', 156),
             ('spiderman', 2),
             ('2', 509),
             ('reignited', 1),
             ('uuuh', 2),
             ("that'm", 1),
             ('not', 675),
             ('through', 74),
             ('with', 976),
             ('either', 25),
             ('ciaranstrange', 3),
             ('sasspiria', 1),
             ('playstation', 94),
             ('bleh', 2),
             ('holy', 35),
             ('shit', 304),
             ('what', 328),
             ('world', 126),
             ('we', 426),
             ('omg', 28),
             ('dreamcatcher', 1),
             ('x', 145),
             ('league', 129),
             ('federals', 1),
             ('cruises', 1),
             ('paybackindia', 2),
             ('50', 18),
             ('it', 1622),
             ('also', 165),
             ('received', 28),
             ('an', 352),
             ('amazon', 281),
             ('e', 36),
             ('voucher', 2),
             ('offering', 3),
             ('inr', 2),
             ('500', 12),
             ('as', 447),
             ('payback', 5),
             ('rewards', 42),
             ('if', 400),
             ('don’t', 42),
             ('come', 103),
             ('ain’t', 6),
             ('buying', 26),
             ('china', 19),
             ('closes\xa0foxconn', 1),
             ('johnson', 417),
             ('and', 2931),
             ('samsung', 13),
             ('factories', 4),
             ('amid', 7),
             ('virus', 13),
             ('outbreak\xa0', 1),
             ('libertarianhub', 2),
             ('2020', 173),
             ('01', 17),
             ('27', 5),
             ('chi…', 1),
             ('https', 273),
             ('t', 411),
             ('co', 303),
             ('cltmh7bc2m', 2),
             ('just', 738),
             ('spent', 26),
             ('hour', 38),
             ('at', 536),
             ('home', 218),
             ('depot', 144),
             ('renovating', 1),
             ('house', 27),
             ('expensive', 12),
             ('hell', 68),
             ('closer', 2),
             ('birthday', 29),
             ('cool', 81),
             ('exhausted', 5),
             ('from', 477),
             ('work', 153),
             ('week', 65),
             ('probably', 71),
             ('stream', 82),
             ('today', 181),
             ('i’m', 149),
             ('stoked', 4),
             ('ok', 42),
             ('dont', 69),
             ('care', 97),
             ('charge', 10),
             ('me', 749),
             ('70', 19),
             ('too', 147),
             ('toxic', 18),
             ('masculinity', 4),
             ('sent', 20),
             ('specifically', 1),
             ('searching', 7),
             ('“men’s', 2),
             ('hair', 12),
             ('again', 177),
             ('d', 46),
             ('mean', 39),
             ('midterms', 2),
             ('because', 252),
             ('it’s', 100),
             ('late', 36),
             ('tired', 26),
             ('atvi', 2),
             ('update', 127),
             ('their', 184),
             ('most', 172),
             ('popular', 6),
             ('hearthstone', 101),
             ('is', 1923),
             ('investors', 10),
             ('should', 111),
             ('satisfied', 2),
             ('amount', 12),
             ('things', 69),
             ('company', 71),
             ('doing', 75),
             ('make', 168),
             ('more', 353),
             ('every', 158),
             ('happy', 134),
             ('enthusiastic', 3),
             ('jerseyboys', 1),
             ('now', 458),
             ('represented', 1),
             ('fb', 10),
             ('welcome', 22),
             ('chucky', 1),
             ('csgo', 84),
             ('our', 172),
             ('chef', 1),
             ('offer', 18),
             ('content', 38),
             ('various', 3),
             ('such', 99),
             ('warcraft', 116),
             ('cs', 47),
             ('valorant', 22),
             ('click', 15),
             ('here', 164),
             ('channel', 26),
             ('tinyurl', 11),
             ('y5gm9h74', 1),
             ('«', 7),
             ('weapon', 13),
             ('development', 7),
             ('sunsetting', 1),
             ('systems', 9),
             ('best', 266),
             ('news', 148),
             ("i've", 140),
             ('heard', 20),
             ('long', 85),
             ('time', 355),
             ('those', 71),
             ('that', 1152),
             ('play', 425),
             ('any', 135),
             ('multi', 4),
             ('major', 35),
             ('season', 67),
             ('strategy', 6),
             ('plan', 22),
             ('involved', 5),
             ('know', 149),
             ('transformation', 1),
             ('needed', 16),
             ('can', 378),
             ('relate', 2),
             ('glorious', 2),
             ('days', 88),
             ('mtg', 4),
             ('bring', 30),
             ('versatile', 2),
             ('creative', 7),
             ('builds', 1),
             ('problems', 42),
             ('sexual', 3),
             ('assaults', 1),
             ('educational', 3),
             ('institutions', 1),
             ('pia', 1),
             ('fake', 21),
             ('licenses', 2),
             ('baloch', 1),
             ('students', 15),
             ('arrested', 3),
             ('protested', 1),
             ('against', 60),
             ('inaccessibility', 1),
             ('215k', 1),
             ('corona', 4),
             ('cases', 2),
             ('rising', 4),
             ('christian', 2),
             ('man', 122),
             ('shot', 36),
             ('he', 149),
             ('had', 213),
             ('bought', 47),
             ('muslim', 2),
             ('majority', 1),
             ('steps', 6),
             ('taken', 37),
             ('ban', 52),
             ('pubg', 172),
             ('3', 325),
             ('these', 173),
             ('even', 235),
             ('wore', 3),
             ('tannis', 2),
             ('her', 87),
             ('handsome', 6),
             ('jack', 4),
             ('want', 148),
             ('report', 19),
             ('racist', 16),
             ('uses', 5),
             ('vile', 1),
             ('words', 6),
             ('harass', 2),
             ('legends', 145),
             ("person's", 1),
             ('id', 27),
             ('gotcha', 1),
             ('uwu', 5),
             ('xd', 11),
             ('20', 95),
             ('series', 139),
             ('dlss', 1),
             ('0', 60),
             ('graphics', 46),
             ('processors', 1),
             ('run', 40),
             ('4k', 11),
             ('speeds', 11),
             ('than', 176),
             ('60', 22),
             ('frames', 3),
             ('per', 13),
             ('second', 44),
             ('according', 6),
             ('nvidia', 200),
             ('pcg', 1),
             ('au', 7),
             ('death', 24),
             ('stran', 1),
             ('why', 300),
             ('two', 62),
             ('year', 144),
             ('old', 81),
             ('them', 210),
             ('same', 84),
             ('youtube', 116),
             ('videos', 25),
             ('ten', 10),
             ('after', 190),
             ('bored', 8),
             ('assassins', 59),
             ('creed', 119),
             ('12', 43),
             ('great', 246),
             ('finished', 42),
             ('off', 115),
             ('last', 143),
             ('red', 228),
             ('dead', 250),
             ('redemption', 156),
             ('legendary', 14),
             ('animal', 10),
             ('pre', 41),
             ('epilogue', 2),
             ('good', 421),
             ('style', 7),
             ('pic', 491),
             ('twitter', 486),
             ('uyo0gbr2bd', 1),
             ('never', 168),
             ('miss', 65),
             ('follow', 27),
             ('current', 21),
             ('updates', 39),
             ('tech', 26),
             ('covid', 53),
             ('19', 60),
             ('comments', 16),
             ('etc', 12),
             ('exc', 1),
             ('playhearthstone', 46),
             ('legit', 11),
             ('disable', 6),
             ('djinn', 1),
             ('asap', 2),
             ('crony', 1),
             ('lame', 6),
             ('boring', 18),
             ('duvalmagic', 7),
             ('gearboxofficial', 14),
             ('wanted', 43),
             ('say', 134),
             ('saying', 38),
             ('huge', 36),
             ('thank', 162),
             ('worked', 25),
             ('working', 78),
             ('wheels', 2),
             ('gearbox', 6),
             ('’', 291),
             ('ve', 31),
             ('been', 311),
             ('crushing', 6),
             ('enven', 2),
             ('months', 33),
             ('before', 97),
             ('knowing', 11),
             ('must', 36),
             ('have', 781),
             ('real', 67),
             ('difficult', 15),
             ('biggest', 17),
             ('fifa', 175),
             ('21', 57),
             ('downgrades', 1),
             ('⏬', 1),
             ('1', 244),
             ('collab', 2),
             ('f', 24),
             ('sebfut', 1),
             ('waht', 3),
             ('kill', 44),
             ('store', 117),
             ("it's", 301),
             ('five', 15),
             ('kid', 7),
             ('microsoft', 280),
             ('wants', 16),
             ('backwards', 4),
             ('compatible', 15),
             ('console', 59),
             ('mobilesyrup', 2),
             ('05', 14),
             ('28', 13),
             ('mic…', 2),
             ('�', 3),
             ('switched', 8),
             ('got', 239),
             ('galaxy', 6),
             ('note20', 1),
             ('ultra', 5),
             ('decision', 26),
             ('made', 106),
             ("y'all", 54),
             ("ain't", 7),
             ('help', 126),
             ('bokchoy', 1),
             ('request', 12),
             ('forget', 13),
             ('gonna', 88),
             ('google', 209),
             ('tube', 1),
             ('cook', 3),
             ('nasty', 10),
             ('kissing', 1),
             ('rt', 17),
             ('cragon', 1),
             ('myself', 35),
             ('dracula', 1),
             ('masquerade', 2),
             ('origins', 6),
             ('deus', 1),
             ('ex', 8),
             ('human', 16),
             ('revolution', 2),
             ('harry', 3),
             ('breath', 6),
             ('og', 7),
             ('leisure', 1),
             ('suit', 6),
             ('corps', 4),
             ("don't", 152),
             ('judge', 5),
             ('fluffbrawl', 1),
             ('killerxkween91', 1),
             ('itslexitaylor', 1),
             ('jbirdsgaming', 1),
             ('wtty', 1),
             ('gamewrexham', 1),
             ('gamedigital', 1),
             ('email', 21),
             ('stay', 32),
             ('safe', 22),
             ('thanks', 149),
             ('industry', 6),
             ('uk', 67),
             ('restart', 16),
             ('by', 302),
             ('9th', 2),
             ('gen', 40),
             ('still', 308),
             ('iffy', 1),
             ('malphite', 1),
             ('shard', 2),
             ('art', 21),
             ('war', 77),
             ('monolith', 1),
             ('always', 110),
             ('hard', 62),
             ('pick', 18),
             ('attack', 10),
             ('physical', 9),
             ('defense', 19),
             ('magic', 9),
             ('difficulty', 4),
             ('life', 75),
             ('give', 83),
             ('700', 4),
             ('bad', 176),
             ("can't", 205),
             ('dang', 7),
             ('thing', 106),
             ('stock', 22),
             ('plz', 27),
             ('bleepincomputer', 1),
             ('flash', 3),
             ('released', 27),
             ('security', 19),
             ("mysterious'spoofing", 1),
             ("virus'", 1),
             ('windows', 45),
             ('11', 25),
             ('tracked', 1),
             ('cve', 1),
             ('1464', 1),
             ('mention', 10),
             ('discovered', 7),
             ('version', 23),
             ('acknowledgement', 2),
             ('page', 23),
             ('ir', 1),
             ('msrc', 1),
             ('en', 27),
             ('us', 215),
             ('security…', 1),
             ('…', 171),
             ('youre', 5),
             ('throttling', 3),
             ('shame', 16),
             ('schooling', 1),
             ('people', 335),
             ('option', 23),
             ('nothing', 76),
             ("nvidia's", 9),
             ('shares', 9),
             ('rises', 4),
             ('toward', 2),
             ('record', 10),
             ('high', 48),
             ('bernstein', 1),
             ('turns', 9),
             ('bullish', 2),
             ('cuts', 3),
             ('price', 47),
             ('target', 11),
             ('mktw', 1),
             ('net', 40),
             ('32fx3km', 1),
             ('initial', 3),
             ('state', 21),
             ('alabama', 1),
             ('blank', 6),
             ('im', 69),
             ('wasting', 3),
             ('dota', 69),
             ('chick', 3),
             ('insane', 27),
             ('makes', 67),
             ('upgrade', 13),
             ('gpu', 21),
             ('video', 146),
             ('inside', 18),
             ('crashes', 19),
             ('would', 188),
             ('call', 147),
             ('videogamecrashception', 1),
             ('need', 115),
             ('leo', 3),
             ('youtu', 116),
             ('h9jup8kt9wu', 1),
             ('beautiful', 53),
             ('online', 94),
             ('order', 49),
             ('homedepot', 40),
             ('perfect', 53),
             ('→', 6),
             ('eljeeeey', 1),
             ('entering', 17),
             ('grand', 48),
             ('summoners', 23),
             ('watch', 135),
             ('won', 64),
             ('100', 79),
             ('gift', 31),
             ('card', 81),
             ('retweet', 28),
             ('everyday', 16),
             ('another', 126),
             ('chance', 64),
             ('win', 113),
             ('gs', 18),
             ('global', 27),
             ('free', 107),
             ('golden', 19),
             ('kamuy', 7),
             ('unit', 23),
             ('ylnbixjdii', 1),
             ('tile', 3),
             ('enjoyable', 7),
             ('wonderful', 14),
             ('hotel', 2),
             ('throughout', 11),
             ('madden', 50),
             ('nfl', 22),
             ('4', 177),
             ('ps4', 47),
             ('39', 3),
             ('95', 6),
             ('ebay', 13),
             ('39mum0q', 1),
             ('month', 46),
             ('back', 234),

In [44]:
tokenizer.document_count

8128

In [45]:
len(tokenizer.word_index)

14738

In [46]:
sequences=tokenizer.texts_to_sequences(data['Tweets'])

In [51]:
sequences[2
          ]

[53]

In [52]:
from keras.utils import pad_sequences

In [53]:
sequences=pad_sequences(sequences,padding='pre')

In [54]:
sequences

array([[   0,    0,    0, ...,   99,  187, 2071],
       [   0,    0,    0, ...,    7, 1889, 3059],
       [   0,    0,    0, ...,    0,    0,   53],
       ...,
       [   0,    0,    0, ...,  175,  149,  516],
       [   0,    0,    0, ...,   81, 1996, 7576],
       [   0,    0,    0, ..., 3067, 4530, 3957]],
      shape=(8128, 74), dtype=int32)

In [55]:
from tensorflow.keras.layers import SimpleRNN,Dense,Input,Embedding
from tensorflow.keras.models import Sequential

In [56]:
X=sequences
Y=data['Sentiment'].values

In [57]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [58]:
model=Sequential()

In [59]:
model.add(SimpleRNN(32,input_shape=(99,1), return_sequences=False))
model.add(Dense(3,activation='softmax'))

c:\Users\a810557\akash\LangchainUpdated\.venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [60]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,187 (4.64 KB)

 Trainable params: 1,187 (4.64 KB)

 Non-trainable params: 0 (0.00 B)

In [61]:
model.compile(optimizer='adam',metrics=['accuracy'],loss='sparse_categorical_crossentropy')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [62]:
model.fit(X_train,Y_train,epochs=5, validation_data=(X_test,Y_test), batch_size=64)

Epoch 1/5
102/102 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.3510 - loss: 1.1560 - val_accuracy: 0.3622 - val_loss: 1.0964
Epoch 2/5
102/102 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - accuracy: 0.3617 - loss: 1.0913 - val_accuracy: 0.3629 - val_loss: 1.0956
Epoch 3/5
102/102 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.3697 - loss: 1.0928 - val_accuracy: 0.3549 - val_loss: 1.0974
Epoch 4/5
102/102 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.3693 - loss: 1.0929 - val_accuracy: 0.3659 - val_loss: 1.0961
Epoch 5/5
102/102 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - accuracy: 0.3671 - loss: 1.0931 - val_accuracy: 0.3604 - val_loss: 1.0943

In [63]:
vocab_size=len(tokenizer.word_index)+1

In [64]:
model_2=Sequential()
model_2.add(Input(shape=(99,1)))
model_2.add(Embedding(input_dim=vocab_size,output_dim=64))
model_2.add(Dense(3,activation='softmax'))

In [66]:
model_2.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 99, 1, 64)      │       943,296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 99, 1, 3)       │           195 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 943,491 (3.60 MB)

 Trainable params: 943,491 (3.60 MB)

 Non-trainable params: 0 (0.00 B)

In [67]:
model_2.compile(optimizer='adam',metrics=['accuracy'],loss='sparse_categorical_crossentropy')

In [ ]:
model_2.fit(X_train,Y_train,epochs=3,validation_data=(X_test,Y_test),batch_size=64)

Epoch 1/3

ValueError: Argument `output` must have rank (ndim) `target.ndim - 1`. Received: target.shape=(None,), output.shape=(None, 74, 1, 3)

In [69]:
model_final=Sequential([Embedding(input_dim=vocab_size,output_dim=128,input_length=99,mask_zero=True),SimpleRNN(32),Dense(3,activation='softmax')])

c:\Users\a810557\akash\LangchainUpdated\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [70]:
model_final.compile(optimizer='adam',metrics=['accuracy'],loss='sparse_categorical_crossentropy')

In [71]:
model_final.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [73]:
model_final.fit(X_train,Y_train,epochs=3,validation_data=(X_test,Y_test),batch_size=32)

Epoch 1/3
204/204 ━━━━━━━━━━━━━━━━━━━━ 17s 64ms/step - accuracy: 0.5632 - loss: 0.9444 - val_accuracy: 0.6765 - val_loss: 0.7822
Epoch 2/3
204/204 ━━━━━━━━━━━━━━━━━━━━ 13s 65ms/step - accuracy: 0.8736 - loss: 0.3759 - val_accuracy: 0.7017 - val_loss: 0.7568
Epoch 3/3
204/204 ━━━━━━━━━━━━━━━━━━━━ 15s 73ms/step - accuracy: 0.9628 - loss: 0.1199 - val_accuracy: 0.6913 - val_loss: 0.8335

In [74]:
import pickle

with open('tokenizer.pkl','wb') as file:
    pickle.dump(tokenizer,file)

model_final.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.